#!/bin/bash
set -euo pipefail
task_root="$(cd "$(dirname "$0")/../.." && pwd)"
task_build="$(mktemp -d /private/tmp/codex-pacer-island-build.XXXXXX)"
task_app="$task_build/Codex Pacer Island.app"
task_output="$task_root/output/island-preview/Codex Pacer Island.app"
mkdir -p "$task_build/native" "$task_app/Contents/MacOS" "$task_app/Contents/Resources"
export CLANG_MODULE_CACHE_PATH="$task_build/module-cache"
export SWIFTPM_MODULECACHE_OVERRIDE="$task_build/module-cache"
rsync -a --exclude=.build --exclude=.swiftpm "$task_root/native/" "$task_build/native/"
swift build --package-path "$task_build/native" --scratch-path "$task_build/.build" --cache-path "$task_build/cache" --config-path "$task_build/config" --security-path "$task_build/security" -c release
cp -X "$task_build/.build/release/CodexPacerIsland" "$task_app/Contents/MacOS/CodexPacerIsland"
cp -X "$task_root/src-tauri/icons/icon.icns" "$task_app/Contents/Resources/Pacer.icns"
cp -X "$task_root/native/Info.plist" "$task_app/Contents/Info.plist"
codesign --force --sign - "$task_app"
codesign --verify --strict "$task_app"
mkdir -p "$(dirname "$task_output")"
ditto --norsrc --noextattr "$task_app" "$task_output"
# The output is generated by this script. Remove metadata retained by a previous
# iCloud copy before validating its signature; never touch source files or apps.
xattr -cr "$task_output"
codesign --verify --strict "$task_output"
printf 'Preview app: %s\n' "$task_output"
printf 'Build directory: %s\n' "$task_build"
